Repository Astha369/CPP_Problems, pull requests merged in 2023-10, with the labels that each got.

#2 prakhar7017-valid_anagram
  Valid_Anagram.cpp
Labels: hacktoberfest-accepted

#4 prakhar7017-Longest_Common_Prefix
  Longest_Common_Prefix.cpp
Labels: hacktoberfest-accepted

#3 factorial.cpp
  factorial.cpp
Labels: hacktoberfest-accepted

#6 Create flatteningbinarytree.cpp
  flatteningbinarytree.cpp
Labels: hacktoberfest-accepted

#11 Vatsalya vyas
  STL_Linkedlist.cpp
  STL_Linkedlist.exe
Labels: hacktoberfest-accepted

#10 prakhar-7017_Isomorphic_String
  Isomorphic_strings.cpp
Labels: hacktoberfest-accepted

#9 Added a CPP file which checks Palindrome using Stack
  Palindrome.cpp
Labels: hacktoberfest-accepted

#15 prakhar7017-Group_Anagrams
  Group_Anagrams.cpp
Labels: hacktoberfest-accepted

#14 a cpp program that generates the Fibonacci series up to given input number.
  Factoial_upto.cpp
Labels: hacktoberfest-accepted

#12 feat: add new C++ program
  recursive.cpp
Labels: hacktoberfest-accepted

#17 Added a code for longest common subsequence (Leetcode: medium)
  longest_common_subsequence.cpp
Labels: hacktoberfest-accepted

#20 CPP solution for average waiting time added
  AverageWaitingTime.cpp
Labels: hacktoberfest-accepted

#21 Added the program that calculates diameter of a tree
  Diameter_Of_Tree.cpp
Labels: hacktoberfest-accepted, issue-resolved

#23 File Renamed from: Factiol_upto -> fibonacci_series_upto [code file uploaded by me]
  Fibonacci_series_upto.cpp
  student_grade_system.cpp
Labels: enhancement

#31 Added cpp solution for integer break
  IntegerBreak.cpp
Labels: hacktoberfest-accepted, cpp

#29 solution for search in a rotated sorted array
  Search_in_a_rotated_sorted_array.cpp
Labels: hacktoberfest-accepted

#37 Heap Sort Program
  Heap_Sort.cpp
  Merge_Sort.cpp
  removeDuplicate.cpp
Labels: hacktoberfest-accepted

#36 issue #27 resolved
  String_to_Int_to_Roman.cpp
  String_to_Int_to_Roman.exe
Labels: hacktoberfest-accepted

#35 Shell Sort Program
  Merge_Sort.cpp
  Shell_Sort.cpp
Labels: hacktoberfest-accepted

#33 Merge Sort Algorithm
  Merge_Sort.cpp
  Quick_Sort.cpp
Labels: hacktoberfest-accepted

#39 Create Rotate_LinkedList_K_Times.cpp
  Rotate_LinkedList_K_Times.cpp
Labels: hacktoberfest-accepted

#41 Compilation of RADIX SORT algorithm
  RADIX_SORT.cpp
Labels: hacktoberfest-accepted

#45 olve/Code to Rotate a LinkedList K times. #32
  Rotate_LinkedList_K_Times.cpp
Labels: hacktoberfest-accepted

#43 Dsa
  .cph/.Valid_Anagram.cpp_0c4570d3a72d043a000b094827d58b0e.prob
  .vscode/tasks.json
  AverageWaitingTime.cpp
  AverageWaitingTime.exe
  Palindrome.cpp
  Palindrome.exe
  Quick_Sort.cpp
  Valid_Anagram.cpp
  Valid_Anagram.exe
Labels: enhancement, hacktoberfest-accepted, issue-resolved

#49 Implemented Max Dot Product of Two Subsequence #48
  Max-Dot-Product of-Two-Subsequence.cpp
Labels: hacktoberfest-accepted, cpp

#51 TopologicalSort
  Topological_sort.cpp
Labels: hacktoberfest-accepted

#50 DisJointSetUnion(DSU)
  Disjoint_Set_Union.cpp
Labels: hacktoberfest-accepted

#54 leetcode problem 8th October 2023 by Adit Kaushal
  leetcode8thOct.cpp
Labels: question, hacktoberfest-accepted

#55 Create build_arraywhere-you-can-find-the-maximum-exactly-k-comparison…
  build_arraywhere-you-can-find-the-maximum-exactly-k-comparisons.cpp
Labels: hacktoberfest-accepted, cpp

#59 Create ThreeSumClosest.cpp
  ThreeSumClosest.cpp
Labels: hacktoberfest-accepted

#64 Added c++ solution for stack with increment operation
  stack_with_increment.cpp
Labels: hacktoberfest-accepted, cpp

#67 Added solution for maximum odd binary number
  max_odd_binary_number.cpp
Labels: hacktoberfest-accepted

#65 Create Problem #63 Array is monoatomic
  Problem #63 Array is monoatomic
Labels: hacktoberfest-accepted

#68 Reverse_integer.c
  Reverse_integer.c
Labels: hacktoberfest-accepted

#74 Add files via upload
  MAX_dot.cpp
Labels: hacktoberfest-accepted

#72 added string maniulation algo
  stringManipulation.cpp
Labels: hacktoberfest-accepted

#75 Create Algorithm of BFS and DFS
  Algorithm of BFS and DFS
Labels: hacktoberfest-accepted, cpp, Important

#76 #73 Number of flowers in full bloom - leetcode daily 11 oct
  flowersinfullbloom.cpp
Labels: hacktoberfest-accepted, cpp

#77 Added Longest Palindromic Substring
  LongestPalindromicSubstring.cpp
  LongestSubstringWithoutRepeatingCharacters.cpp
Labels: hacktoberfest-accepted

#87 Create LetterCombinationsofPhoneNumber.cpp
  LetterCombinationsofPhoneNumber.cpp
Labels: hacktoberfest-accepted, cpp

#81 Create Reverse_Integer.cpp
  Reverse_Integer.cpp
Labels: hacktoberfest-accepted

#88 Merge Two Sorted Lists
  mergeTwoSortedLists.cpp
Labels: hacktoberfest-accepted

#89 Create min_in_rotated_sorted_array
  min_in_rotated_sorted_array
Labels: hacktoberfest-accepted

#94 Create Is_graph_bipartite.cpp
  Is_graph_bipartite.cpp
Labels: hacktoberfest-accepted

#91 Create remove_coloured_pieces.cpp
  remove_coloured_pieces.cpp
Labels: hacktoberfest-accepted

#99 Graph algorithms
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  Dijkstra algorithm.cpp
  Fibonacci using dp.cpp
  prims algorithm.cpp
Labels: hacktoberfest-accepted, cpp

#109 AVL-Trees/insertion
  Trees/AVL tree/AVL-learn.md
  Trees/AVL tree/AVL.cpp
  Trees/Binary tree/binaryTreeInorderTraversal.cpp
  Trees/Binary tree/flatteningbinarytree.cpp
Labels: hacktoberfest-accepted, cpp
